In [12]:
import numpy as np

if __name__ == "__main__":
    
    arr = np.arange(1,5).reshape(2,2)
    arr_evalues,arr_evectors = np.linalg.eig(arr)
    arr_det = round(np.linalg.det(arr),8)
    print("Eigenvalues: \n",arr_evalues)
    print("Egernvectors: \n",arr_evectors)
    print("Determinant: \n",arr_det)
    
    vec1 = np.arange(1,4)
    vec2 = np.arange(4,7)
    cross1_2 = np.cross(vec1,vec2)
    print("Cross product: \n",cross1_2)
    
    A = np.array([[1,2,-2],[2,1,-5],[1,-4,1]])
    b = np.array([-15,-21,18]).reshape(3,1)
    x = np.linalg.solve(A,b)
    print("Solution: \n",x)
    
    


Eigenvalues: 
 [-0.37228132  5.37228132]
Egernvectors: 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Determinant: 
 -2.0
Cross product: 
 [-3  6 -3]
Solution: 
 [[-1.]
 [-4.]
 [ 3.]]
